variables:
  PKGNAME:     "OUTRIDER"
  PKGDIR:      "./"
  R_LIBS_U:    "tmp_lib"
  # RVER:        "3.5.0-Bioc3.7"
  RVER:        "000-devel-3.5.0-Bioc3.8"
  TEXVER:      "2016"
  # CI_DEBUG_TRACE: "true"

stages:
  - testing

before_script:
  - module load "i12g/R/$RVER"
  - module load "i12g/texlive/$TEXVER"
  - export R_LIBS_U="`realpath ${CI_JOB_ID}_${R_LIBS_U}`"
  - mkdir $R_LIBS_U
  - R --vanilla CMD build --no-build-vignettes --no-manual $PKGDIR
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R_LIBS_USER=$R_LIBS_U Rscript --vanilla -e "install.packages('${PKG_FILE_NAME}', lib='$R_LIBS_U', repo=NULL)"

R-check:
  stage: testing
  when: always
  tags: [shell]
  script:
    - R_LIBS_USER=$R_LIBS_U R --vanilla CMD check --no-vignettes --timings "${PKG_FILE_NAME}"

R-BiocCheck:
  stage: testing
  when: always
  tags: [shell]
  script:
    - R_LIBS_USER=$R_LIBS_U R --vanilla CMD BiocCheck --no-check-vignettes "${PKG_FILE_NAME}"

R-coverage:
  stage: testing
  when: always
  tags: [shell]
  script:
    - R_LIBS_USER=$R_LIBS_U Rscript --vanilla -e "library('$PKGNAME'); covr::package_coverage('$PKGDIR')"

R-check_vignettes:
  stage: testing
  when: always
  tags: [shell]
  script:
    - cd "$PKGDIR/vignettes/" && R_LIBS_USER=$R_LIBS_U R --vanilla CMD Sweave --engine=knitr::knitr --pdf "$PKGNAME.Rnw"
