# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

truncLogLiklihood <- function(k, x, W, b, s, theta) {
    .Call('_OUTRIDER_truncLogLiklihood', PACKAGE = 'OUTRIDER', k, x, W, b, s, theta)
}

gradLogLiklihood <- function(k, x, W, b, s, theta) {
    .Call('_OUTRIDER_gradLogLiklihood', PACKAGE = 'OUTRIDER', k, x, W, b, s, theta)
}

