# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

armaMatMult <- function(A, B) {
    .Call('_OUTRIDER_armaMatMult', PACKAGE = 'OUTRIDER', A, B)
}

armaMatMultAtBC <- function(A, B, C) {
    .Call('_OUTRIDER_armaMatMultAtBC', PACKAGE = 'OUTRIDER', A, B, C)
}

armaMatMultABBt <- function(A, B) {
    .Call('_OUTRIDER_armaMatMultABBt', PACKAGE = 'OUTRIDER', A, B)
}

